[package]
name = "rustinstallarch"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono-tz = "0.9.0"
nix = { version = "0.28.0", features = [ "process", "fs" ] }
serde = { version = "1.0.202", features = [ "derive" ] }
serde_json = "1.0.117"
