name: CI/CD Rust Arch Install Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Update Rust and Dependencies
      run: |
        rustup update stable && rustup default stable
        

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-


    - name: Run tests
      run: |
        cargo update --verbose
        cargo build --verbose
        cargo test --verbose

    - name: Build project
      run: cargo build --release

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/rustinstallarch:dev

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/rustinstallarch:dev
